#!/usr/bin/python3
import random

def zyanken(x,y):
    xa = x + 1
    if xa>3:
        xa -= 3

    xb = x + 2
    if xb>3:
        xb -= 3

    if xa == y:
        ans = 1
    elif xb == y:
        ans = -1
    else:
        ans = 0

    return ans

def otete(x):
    if x == 1:
        print("私はグーを出したよ！")
    elif x == 2:
        print("私はチョキを出したよ！")
    elif x == 3:
        print("私はパーを出したよ！")

    return

def muitahou(x):
    if x == 1:
        print("私は左を向いたよ！")
    elif x == 2:
        print("私は上をむいたよ！")
    elif x == 3:
        print("私は下を向いたよ！")
    elif x == 4:
        print("私は右を向いたよ！")

    return

def sasitahou(x):
    if x == 1:
        print("左向いちゃったね！")
    elif x == 2:
        print("上向いちゃったね！")
    elif x == 3:
        print("下向いちゃったね！")
    elif x == 4:
        print("右向いちゃったね！")

    return

def sasita(x):
    if x == 1:
        print("私は左を指したよ！")
    elif x == 2:
        print("私は上を指したよ！")
    elif x == 3:
        print("私は下を指したよ！")
    elif x == 4:
        print("私は右を指したよ！")

    return

q = 0
while q==0: 
    i = 0
    while i==0:
        print("じゃんけん")
        print("1:グー　2:チョキ　3:パー")
        num = random.randint(1,3)
        print("何を出しますか？")
        x = input()
        y = int(x)
        
        while y>3:
            y-=3 

        result = zyanken(y,num)
        
        if result == 1:
            otete(num)
            print("あなたの勝ち\n")
            i = 1
        elif result == -1:
            otete(num)
            i = 1
            print("あなたの負け\n")
        else:
            otete(num)
            print("引き分け\n")

    print("あっちむいてほい")
    print("1:←　2:↑　3:↓　4:→")
    if result==1:
        print("どっちを指しますか？")
    else:
        print("どっちを向きますか？")

    num = random.randint(1,4)
    x = input()
    y = int(x)

    while y>4:
            y-=4

    if y == num:
        if result==1:
            muitahou(num)
            print("あなたの勝ち！")
            q = 1
        else:
            sasitahou(num)
            print("あなたの負け！")
            q = 1
    else:
        if result == 1:
            muitahou(num)
            print("まだ遊べるね！\n")
        else:
            sasita(num)
            print("まだ遊べるね！\n")
