#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Chuma Naoki
# SPDX-License-Identifier: BSD-3-Clause 
import sys

alphabet = ["A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#" ]

x = float(sys.stdin.read())
num = 440.0
num2 = 0.0
num3 = 32.703
kenban = 0
onkai = 0
onkai1 = 0
onkai2 = 0

if x<27.5:
    sys.stderr.write('エラーが発生しました。\n')
    sys.exit(1)

if x>32.703:
    while num3 < x:
        num3 *= 2
        onkai += 1

if x>=440:
    while num <= x:
        num *= 2
        onkai1 += 1
    num /= 2
    onkai1 -= 1

if x<440:
    while num > x:
        num /= 2
        onkai1 -= 1

if num < x:
    while num < x:
        num *= 1.0594630943
        onkai2 += 1
    onkai2 -= 1
    num /= 1.0594630943

kenban = 49 + ((onkai1 * 12)  + (onkai2 * 1))

num2 = (num * 1.0594630943) - 0.01

print(f'{kenban} {alphabet[onkai2]}{onkai} {round(num,2)} {round(num2,2)}')

    
